# .github/workflows/cpp-ci.yml
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libglfw3-dev \
          libgl1-mesa-dev \
          xorg-dev \
          pkg-config

    - name: Build
      working-directory: ./src
      run: |
        make clean
        make

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TemuBuku
        path: src/bin/TemuBuku
